# Generated by Django 2.1.14 on 2019-11-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191120_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.CharField(choices=[('Data', 'Data Science'), ('Web', 'Full Stack')], default='Web', max_length=255),
        ),
    ]
